### ISSUE TITLE
support prettier-eslint?

### ISSUE THREAD

**Issue by kentcdodds** [noyobo/prettier-markdown#5]
Would you be interested in adding support for opt-in prettier-eslint? I'd be happy to make the PR!

Thanks! This is so great :)

**Comment by noyobo** [comment]
At first, I did this tool just for simple formatting of Markdown (used prettier default options),  `prettier-eslint`  has a richer configuration,  But do we really need it?  In the case.

**Comment by kentcdodds** [comment]
I can understand your desire to keep this as simple as possible. The nice thing is that most folks could keep the simplicity and not provide any options and get really nice prettier output. For folks who already have ESLint set up to lint their own code, they could enable eslint integration (via an `--eslint` flag or maybe we could expose a `prettier-eslint-markdown` binary in addition) and the formatting in their markdown would match the formatting of their codebase. The added complexity to this codebase and to the API would be quite minimal.

But either way, I'm happy to fork this if you'd rather not include it.

**Comment by noyobo** [comment]
Of course, I hope that more people to use this tool, with a strong ability, and can not be configured in any case to meet the simple needs.

While enhancing the ability while keeping it simple, I'd love to see someone to improve **prettier-markdown**.

Welcome PR!

**Comment by kentcdodds** [comment]
I don't use prettier-eslint anymore so I don't need this to be implemented :)
