### ISSUE TITLE
Expose prettier options from CLI

### ISSUE THREAD

**Issue by jmakeig** [noyobo/prettier-markdown#9]
It would be nice to pass options to prettier from the command line. (Thankfully prettier doesn’t have that many.)

**Comment by jmakeig** [comment]
I’ll try to take a crack at this in a PR.

**Comment by noyobo** [comment]
https://github.com/noyobo/prettier-markdown/blob/master/lib/prettier-markdown.js#L37

https://github.com/noyobo/prettier-markdown/blob/master/bin/cli.js#L60

like:

```
pmd *.md --tabWidth=4
```

In fact, it has been supported.

However, I rarely need to modify the default configuration, so no other options are implemented.
